// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXowkQnpfTpMPcrp-ns0DnDlG57RKZCJ8',
    appId: '1:961081196360:web:388f00d38b9930bcaefd7d',
    messagingSenderId: '961081196360',
    projectId: 'chat-app-8aa52',
    authDomain: 'chat-app-8aa52.firebaseapp.com',
    storageBucket: 'chat-app-8aa52.appspot.com',
    measurementId: 'G-BFG79BMLB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgioiZMcFFf0JrMT_PlWXUJWJo--xWa7k',
    appId: '1:961081196360:android:e679fe87b9edfc2aaefd7d',
    messagingSenderId: '961081196360',
    projectId: 'chat-app-8aa52',
    storageBucket: 'chat-app-8aa52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixTRQRGtVXvxjHEmorO3n-sohtejMSSs',
    appId: '1:961081196360:ios:c4b724c97811ce0daefd7d',
    messagingSenderId: '961081196360',
    projectId: 'chat-app-8aa52',
    storageBucket: 'chat-app-8aa52.appspot.com',
    iosClientId: '961081196360-g09bc58ca7cah08ao8c50rurqc4coada.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAixTRQRGtVXvxjHEmorO3n-sohtejMSSs',
    appId: '1:961081196360:ios:c4b724c97811ce0daefd7d',
    messagingSenderId: '961081196360',
    projectId: 'chat-app-8aa52',
    storageBucket: 'chat-app-8aa52.appspot.com',
    iosClientId: '961081196360-g09bc58ca7cah08ao8c50rurqc4coada.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
